### ISSUE TITLE
New weboscket library

### ISSUE THREAD

**Issue by dajuric** [facundofarias/awesome-websockets#11]
Please put the following library (C#):

[WebSocketRPC](https://github.com/dajuric/websocket-rpc) - WebSocket RPC library for .NET with auto JavaScript client code generation, supporting ASP.NET Core.

**Comment by facundofarias** [comment]
Done! 
Thanks @dajuric

**Comment by dajuric** [comment]
Thanks Facundo!

2018-01-15 15:21 GMT+01:00 Facundo Farias <notifications@github.com>:
