### ISSUE TITLE
Command Line Clients

### ISSUE THREAD

**Issue by thehowl** [facundofarias/awesome-websockets#12]
Hey there! Thanks for creating this list. I'm the creator and maintainer of [claws](https://github.com/thehowl/claws), which is an interactive WebSocket command line app. I found out about this list, and was wondering whether my project could be a good fit for it? It doesn't seem to fall in any of the existing categories.

Other similar projects:

* https://github.com/websockets/wscat
* https://github.com/esphen/wsta
* https://github.com/hashrocket/ws
* https://github.com/progrium/wssh
* https://github.com/raphael/wsc
* https://github.com/kseo/ws-cli

**Comment by facundofarias** [comment]
Hi @thehowl!
I think so. We can create a new category for these clients, what do you think?

**Comment by thehowl** [comment]
Sounds great!

**Comment by facundofarias** [comment]
@thehowl Done
Thanks for the suggestion!
