### ISSUE TITLE
We need to replace uws it got disconntinued

### ISSUE THREAD

**Issue by frank-dspeed** [facundofarias/awesome-websockets#17]
uws got deprecated by its main author and is not on npm any more there are backups the creator had the opinion that it is not secure

see the npm message for uws https://www.npmjs.com/package/uws

**Comment by Dmitry-N-Medvedev** [comment]
what about this: https://github.com/uNetworking/uWebSockets.js ?

**Comment by frank-dspeed** [comment]
is the new repo for it yes thats right but it don't gets published to npm anymore

**Comment by Dmitry-N-Medvedev** [comment]
> is the new repo for it yes thats right but it don't gets published to npm anymore

so, npm repo is absolutely required and you will just exclude a brilliant piece of software just because of this?

**Comment by frank-dspeed** [comment]
@Dmitry-N-Medvedev npm gets shipped with node sure we can replace that but it could lead to confusion and it has security issues at present. I am not Sure its your awsome list i only wanted to point that out i did not know how you want to handle that this is why i created a issue and not a PullRequest. :D

**Comment by Dmitry-N-Medvedev** [comment]
okey,
technically, uws should be removed, but a new link to uWebSockets.js should be given instead.

**Comment by facundofarias** [comment]
Hey guys, interesting discussion @frank-dspeed @Dmitry-N-Medvedev.
I agree that we should have another link and remove the one with security concerns.

**Comment by frank-dspeed** [comment]
closed by #18
