### ISSUE TITLE
Please consider to add [LAppS](https://github.com/ITpC/LAppS/)

### ISSUE THREAD

**Issue by pkpro** [facundofarias/awesome-websockets#27]
Hi there,
please consider to add [LAppS](https://github.com/ITpC/LAppS/) to this list. 
LAppS is an application server for Lua and/or C/C++. LAppS to WebSockets is like apache or nginx to HTTP. It is highly scalable, easy to use for the prototyping or for highly scalable C++/Lua applications.

**Comment by facundofarias** [comment]
Done @pkpro, thanks!
